config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  devise_scope :user do
    root to: "devise/sessions#new" # Redirect to Devise login page
  end

  resources :characters do
    member do
      get "dungeon", to: "dungeon#show", as: :dungeon
      get "fight", to: "dungeon#fight", as: :fight
      post "take_turn", to: "dungeon#take_turn", as: :take_turn
      post :heal
      patch "upgrade_spell", to: "characters#upgrade_spell"
      post "take_scroll"
      post "take_item"
      post "learn_scroll"
    end
  end
end

app/controllers/dungeon_controller.rb
class DungeonController < ApplicationController
  before_action :authenticate_user!
  before_action :set_character, only: [ :show, :take_turn ]
  before_action :set_monster, only: [ :take_turn ]

  def show
    @monster = generate_monster(@character.dungeon_stage)
    session[:monster_id] = @monster.id
    session[:monster_health] = @monster.health
    session[:monster_stats] = {
      min_physical_damage: @monster.min_physical_damage,
      max_physical_damage: @monster.max_physical_damage,
      armor: @monster.armor,
      magic_resistance: @monster.magic_resistance
    }
  end

  def fight
    @character = current_user.characters.find(params[:id])
    @monster = Monster.find(params[:monster_id])
    initialize_battle_state
  end


  def take_turn
    @character.turn_start_reduce_cooldowns

    case params[:action_type]
    when "attack"
      character_attack
      if handle_battle_outcomes
        render :fight and return
      end
      toggle_turn
      monster_attack if session[:monster_health] > 0
      if handle_battle_outcomes
        render :fight and return
      end
    when "spell"
      character_spellcast
      if handle_battle_outcomes
        render :fight and return
      end
      toggle_turn
      monster_attack if session[:monster_health] > 0
      if handle_battle_outcomes
        render :fight and return
      end
    when "flee"
      @result = "You fled from the battle!"
      redirect_to dungeon_character_path(@character) and return
    end

    toggle_turn
    render :fight
  end


  private

  def set_character
    @character = current_user.characters.find(params[:id])
  end

  def set_monster
    @monster = Monster.find(session[:monster_id])
  end

  def initialize_battle_state
    @character.spells.where(unlocked: true).update_all(cooldown: 0)

    session[:messages] = nil
    session[:messages] = []
    session[:monster_id] = @monster.id
    session[:monster_health] = @monster.health
    session[:turn] = "character"

    session[:frenzy_stacks] = 0
    session[:frenzy_damage] = 0
  end

  def generate_monster(stage)
    base_health = 100
    min_physical_damage = 15
    max_physical_damage = 20
    base_armor = 5
    base_magic_resistance = 5
    scaling_factor = 1.10
    @monster = Monster.create(
      name: Monster::MONSTER_NAMES.sample,
      health: (base_health * (scaling_factor ** (stage - 1))).to_i,
      max_health: (base_health * (scaling_factor ** (stage - 1))).to_i,
      min_physical_damage: (min_physical_damage * (scaling_factor ** (stage - 1))).to_i,
      max_physical_damage: (max_physical_damage * (scaling_factor ** (stage - 1))).to_i,
      armor: (base_armor * (scaling_factor ** (stage - 1))).to_i,
      magic_resistance: (base_magic_resistance * (scaling_factor ** (stage - 1))).to_i
    )
    @monster.save
    @monster
  end

  def check_attack_status
  end

  def character_attack
    damage_roll = 0
    if %w[warrior rogue].include?(@character.character_class)
      damage_roll =   rand(@character.min_physical_damage..@character.max_physical_damage)
      damage_type = "physical"
    elsif %w[mage].include?(@character.character_class)
      damage_roll =   rand(@character.min_magic_damage..@character.max_magic_damage)
      damage_type = "magic"
    end
    has_crit = false
    if rand(0..100) <= @character.critical_strike_chance
      damage_roll = (damage_roll * @character.critical_strike_damage).to_i
      has_crit = true
    end
    damage = (damage_roll - @monster.armor).to_i
    [ session[:monster_health] -= damage, 0 ].max
    message = "You attack #{@monster.name} for #{damage} #{damage_type} damage!"
    message.prepend("CRITICAL STRIKE! ") if has_crit
    session[:messages] << message
    trim_messages
  end

  def character_spellcast
    damage_roll = 0
    damage = 0
    has_crit = false
    spell_name = params[:spell_name]
    spell = @character.spells.find_by(name: spell_name)
    if @character.cannot_cast?(spell)
      session[:messages] << "You can't cast #{spell_name} right now!"
      return
    end
    @character.mana -= spell.mana_cost
    spell.update(cooldown: spell.base_cooldown)
    if spell.damage_type == "physical"
      damage_roll = ((rand(@character.min_physical_damage..@character.max_physical_damage)) + spell.damage).to_i
        if spell.name == "Frenzy"
          damage_roll = ((rand(@character.min_physical_damage..@character.max_physical_damage) + spell.damage + session[:frenzy_damage])).to_i
          unless session[:frenzy_stacks] >= 5
              session[:frenzy_stacks] += 1
              session[:frenzy_damage] += spell.damage
          end
        end
      if rand(0..100) <= @character.critical_strike_chance
        damage_roll = (damage_roll * @character.critical_strike_damage).to_i
        has_crit = true
      end
      damage = (damage_roll - @monster.armor).to_i
    elsif spell.damage_type == "magic"
      damage_roll = ((rand(@character.min_magic_damage..@character.max_magic_damage)) + spell.damage).to_i
        if rand(0..100) <= @character.critical_strike_chance
          damage_roll = (damage_roll * @character.critical_strike_damage).to_i
          has_crit = true
        end
      damage = (damage_roll - @monster.magic_resistance).to_i
    end
    [ session[:monster_health] -= damage, 0 ].max
    message = "You cast #{spell[:name]} on #{@monster.name} for #{damage} #{spell.damage_type} damage!"
    message.prepend("CRITICAL STRIKE! ") if has_crit
    session[:messages] << message
    trim_messages
  end

  def monster_attack
    damage = [ (rand(@monster.min_physical_damage..@monster.max_physical_damage) - @character.armor), 0 ].max
    @character.update(health: [ @character.health - damage, 0 ].max)
    session[:messages] << "#{@monster.name} attacks you for #{damage} damage!"
    trim_messages
  end

  def handle_battle_outcomes
    if session[:monster_health] <= 0
      xp_gain = (100 * (0.98 ** (@character.level - 1))).to_i
      @character.gain_experience(xp_gain)
      @result = "Victory! You defeated the #{@monster.name}!"
      session[:messages] << "You gained #{xp_gain} experience!"
      @character.update(dungeon_stage: @character.dungeon_stage + 1)
      session[:turn] = nil
      loot = @monster.drop_item_or_scroll(@character)
      session[:loot] = loot unless loot.empty?
      return true
    elsif @character.health <= 0
      @result = "You were defeated by the #{@monster.name}!"
      session[:turn] = nil
      return true
    end
    false
  end

  def trim_messages
    session[:messages] = session[:messages]
  end

  def toggle_turn
    session[:turn] = session[:turn] == "character" ? "monster" : "character"
  end
end

app/helpers/dungeon_helper.rb
module DungeonHelper
end

app/views/dungeon/fight.html.erb
<div class="status">
  <div class="health-bar-container">
    <h2><%= @character.name %></h2>
    <p>Health: <%= @character.health %> / <%= @character.max_health %></p>
    <div class="health-bar">
      <div class="health" id="player-health-bar" style="width: <%= (@character.health.to_f / @character.max_health) * 100 %>%;"></div>
    </div>

    <h2><%= @monster.name %></h2>
    <p>Health: <%= session[:monster_health] %> / <%= @monster.max_health %></p>
    <div class="health-bar">
      <div class="health" id="monster-health-bar" style="width: <%= (session[:monster_health].to_f / @monster.max_health) * 100 %>%;"></div>
    </div>
  </div>
</div>

<br>

<% if @result.present? %>
  <div class="result">
    <p id="battle-result"><%= @result %></p>
    <%= link_to "Continue", dungeon_character_path(@character) %>
  </div>
<% end %>

<br>

<div class="messages">
  <% session[:messages].each do |msg| %>
    <%= msg %>
    <hr>
  <% end %>
</div>

<br>

<% if session[:loot].present? %>
  <% session[:loot].each do |item| %>
    <div>
      <% if item.is_a?(Item) %>
        <p>You have found <%= item.name %></p>
        <%= button_to "Take #{item.name}", take_item_character_path(@character, item_id: item.id), method: :post %>
      <% elsif item.is_a?(Scroll) %>
        <p>You have found <%= item.name %></p>
        <%= button_to "Take #{item.name}", take_scroll_character_path(@character, scroll_id: item.id), method: :post %>
      <% end %>
    </div>
  <% end %>
<% end %>



<div id="actions" class="flex space-x-4">
  <% if session[:turn] == "character" && @character.health > 0 && session[:monster_health] > 0 %>
    <%= form_with url: take_turn_character_path(@character), method: :post do %>
      <%= hidden_field_tag :action_type, "attack" %>
      <%= submit_tag "Attack", class: "btn" %>
    <% end %>
  <br>
  <button id="spells-button" class="btn">Spells</button>
  <div id="spells-list" style="display: none;">
    <% @character.spells.where(unlocked: true).each do |spell| %>
      <div>
        <span><%= spell.name %><br>
        Mana Cost: <%= spell.mana_cost %><br>
        Cooldown: <%= spell.cooldown > 0 ? spell.cooldown : 'Ready' %></span>
        <% if @character.cannot_cast?(spell) %>
          <% if spell.cooldown > 0 %>
            <p>(On cooldown for <%= spell.cooldown %> turns)</p>
          <% elsif @character.mana < spell.mana_cost %>
            <p>(Not enough mana)</p>
          <% end %>
        <% else %>
          <%= form_with url: take_turn_character_path(@character), method: :post do %>
            <%= hidden_field_tag :action_type, "spell" %>
            <%= hidden_field_tag :spell_name, spell.name %>
            <%= submit_tag "Cast #{spell.name}", class: "btn" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <br>
  <%= form_with url: take_turn_character_path(@character), method: :post do %>
    <%= hidden_field_tag :action_type, "flee" %>
    <%= submit_tag "Flee", class: "btn" %>
  <% end %>
  <% end %>
</div>

<script>
  const playerHealthBar = document.getElementById("player-health-bar");
  const monsterHealthBar = document.getElementById("monster-health-bar");

  const currentPlayerHealth = <%= @character.health %>;
  const currentMonsterHealth = <%= session[:monster_health] %>;

  const playerHealthPercent = (currentPlayerHealth / <%= @character.max_health %>) * 100;
  const monsterHealthPercent = (currentMonsterHealth / <%= @monster.max_health %>) * 100;

  playerHealthBar.style.width = playerHealthPercent + "%";
  monsterHealthBar.style.width = monsterHealthPercent + "%";
</script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const spellsButton = document.getElementById("spells-button");
    const spellsList = document.getElementById("spells-list");

    spellsButton.addEventListener("click", function() {
      if (spellsList.style.display === "none") {
        spellsList.style.display = "block";
      } else {
        spellsList.style.display = "none"; 
      }
    });
  });
</script>

app/views/dungeon/show.html.erb
<h1>Dungeon Stage <%= @character.dungeon_stage %></h1>
<p>You have encountered a <%= @monster.name %> in the dungeon!</p>
<p>Stats:</p>
<ul>
  <li>Health: <%= @monster.health %></li>
  <li>Physical Damage: <%= @monster.min_physical_damage %> - <%= @monster.max_physical_damage %></li>
  <li>Magic Damage: <%= @monster.min_magic_damage %> - <%= @monster.max_magic_damage %></li>
  <li>Armor: <%= @monster.armor %></li>
  <li>Magic Resistance: <%= @monster.magic_resistance %></li>
</ul>

<br>

<%= link_to "Fight", fight_character_path(@character, monster_id: session[:monster_id]) %>